import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'travex_settings'

const DEFAULT_SETTINGS = {
  emailBookings: true,
  emailPromos: true,
  inAppNotifications: true,
  compactTables: false,
  theme: 'light',
  language: 'vi',
}

const DICTIONARY = {
  vi: {
    settingsTitle: 'Cài đặt',
    settingsSubtitle: 'Quản lý hồ sơ, bảo mật và cách TraveX gửi thông báo.',
    logout: 'Đăng xuất',
    accountTitle: 'Thông tin tài khoản',
    accountSubtitle: 'Các thông tin này dùng để hiển thị trong hệ thống.',
    fullName: 'Họ tên',
    username: 'Tên đăng nhập',
    phone: 'Số điện thoại',
    saveProfile: 'Lưu hồ sơ',
    securityTitle: 'Bảo mật',
    securitySubtitle: 'Đổi mật khẩu định kỳ để bảo vệ tài khoản.',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Nhập lại mật khẩu mới',
    changePassword: 'Đổi mật khẩu',
    notificationsTitle: 'Thông báo',
    notificationsSubtitle: 'Chọn những cập nhật bạn muốn nhận.',
    bookingEmail: 'Email đặt tour',
    bookingEmailHelp: 'Xác nhận đặt tour, thanh toán và thay đổi lịch trình.',
    promoEmail: 'Email khuyến mãi',
    promoEmailHelp: 'Nhận mã ưu đãi và chiến dịch theo mùa.',
    inAppNotifications: 'Thông báo trong ứng dụng',
    inAppNotificationsHelp: 'Hiển thị nhắc việc và cập nhật mới ngay trong dashboard.',
    appearanceTitle: 'Giao diện',
    appearanceSubtitle: 'Tùy chỉnh cách hiển thị phù hợp thói quen làm việc.',
    theme: 'Chủ đề',
    language: 'Ngôn ngữ',
    systemTheme: 'Theo hệ thống',
    lightTheme: 'Sáng',
    darkTheme: 'Tối',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    compactTables: 'Bảng dữ liệu gọn hơn',
    compactTablesHelp: 'Giảm khoảng cách dòng cho màn hình quản trị.',
    profileSaved: 'Đã lưu thông tin hồ sơ trên thiết bị này.',
    passwordMissing: 'Vui lòng nhập đủ thông tin mật khẩu.',
    passwordShort: 'Mật khẩu mới cần ít nhất 6 ký tự.',
    passwordMismatch: 'Mật khẩu xác nhận chưa khớp.',
    passwordChecked: 'Đã kiểm tra hợp lệ. Kết nối API đổi mật khẩu có thể bổ sung sau.',
    campaignTitle: 'Tour ưu đãi',
    campaignPublicHeadline: 'Các tour đang có giá tốt',
    campaignAdminHeadline: 'Quản lý tour đang khuyến mãi',
    campaignPublicText: 'Chọn nhanh những tour đang giảm giá, xem ưu đãi rõ ràng và đặt lịch cho chuyến đi tiếp theo.',
    campaignAdminText: 'Theo dõi các tour có giá ưu đãi, ngày áp dụng và nội dung khuyến mãi ngay từ dữ liệu tour.',
    viewDeals: 'Xem tour ưu đãi',
    backHome: 'Về trang chủ',
    manageTours: 'Quản lý tour',
    appliedTours: 'Tour áp dụng',
    bestDiscount: 'Ưu đãi cao nhất',
    daysLeft: 'Còn lại',
    days: 'ngày',
    publicCampaignTours: 'Tour đang khuyến mãi',
    adminCampaignTours: 'Tour có ưu đãi',
    publicCampaignHelp: 'Lọc theo điểm đến, loại tour và ngân sách để chọn chuyến đi phù hợp.',
    adminCampaignHelp: 'Lọc nhanh theo nhu cầu để tư vấn hoặc kiểm tra danh sách ưu đãi.',
    searchTour: 'Tìm điểm đến hoặc tên tour',
    maxBudget: 'Ngân sách tối đa',
    loadingCampaign: 'Đang tải tour chiến dịch...',
    emptyCampaign: 'Chưa có tour phù hợp bộ lọc hiện tại.',
    summerPlaceholder: 'Ưu đãi',
    seeAndBook: 'Xem và đặt tour',
    seeDetails: 'Xem chi tiết',
    home: 'Trang chủ',
    tour: 'Tour',
    login: 'Đăng nhập',
    all: 'Tất cả',
    island: 'Biển đảo',
    family: 'Gia đình',
    resort: 'Nghỉ dưỡng',
    explore: 'Khám phá',
    navDashboard: 'Tổng quan',
    navBookings: 'Đặt tour',
    navSchedule: 'Lịch trình',
    navCustomers: 'Khách hàng',
    navReports: 'Doanh thu',
    navVnpay: 'Thanh toán VNPay',
    navUsers: 'Người dùng',
    management: 'Quản lý',
    adminRole: 'Quản trị viên',
    staffRole: 'Hướng dẫn viên',
    customerRole: 'Khách hàng',
    adminSearchPlaceholder: 'Tìm tên khách hàng hoặc tên tour...',
    totalRevenue: 'Tổng doanh thu',
    vsPrevious: 'so với kỳ trước',
    activeTours: 'Tour đang mở',
    closedTours: 'tour đã đóng',
    pendingBookings: 'Đặt tour chờ xử lý',
    requestsNeedReview: 'yêu cầu cần xem',
    vnpayPayments: 'Thanh toán VNPay',
    revenue: 'Doanh thu',
    tourPerformance: 'Hiệu quả tour',
    viewAll: 'Xem tất cả',
    viewAllTours: 'Xem tất cả tour',
    category: 'Danh mục',
    duration: 'Thời gian',
    priceFrom: 'Giá từ',
    bookingCount: 'Lượt đặt',
    status: 'Trạng thái',
    openStatus: 'Đang mở',
    closedStatus: 'Đã đóng',
    recentActivity: 'Hoạt động gần đây',
    newBookingRequest: 'Yêu cầu đặt tour mới',
    paymentReceived: 'Đã nhận thanh toán',
    recentBookings: 'Đặt tour gần đây',
    success: 'Thành công',
    pending: 'Đang chờ',
    totalVnpayRevenue: 'Tổng doanh thu VNPay',
    noVnpayPayments: 'Chưa có giao dịch VNPay.',
    toursListTitle: 'Danh sách tour',
    toursListAdminHelp: 'Quản lý thông tin tour, điểm đến, giá và sức chứa.',
    toursListCustomerHelp: 'Tìm kiếm và đặt các tour du lịch hấp dẫn.',
    searchTourCodeDestination: 'Tìm tour, mã tour, điểm đến...',
    addTour: 'Thêm tour',
    noTours: 'Không có tour nào.',
    destination: 'Điểm đến',
    guests: 'khách',
    capacity: 'Sức chứa',
    noDescription: 'Chưa có mô tả.',
    viewBookTicket: 'Xem chi tiết / Đặt vé',
    departureSchedule: 'Lịch khởi hành',
    edit: 'Sửa',
    delete: 'Xoá',
    myTours: 'Tour của tôi',
    bookingsListTitle: 'Danh sách đặt tour',
    myToursHelp: 'Quản lý các tour bạn đã đặt và thanh toán VNPay.',
    bookingsListHelp: 'Quản lý lượt đặt tour, trạng thái xử lý và thanh toán VNPay.',
    bookTour: 'Đặt tour',
    newBooking: 'Đặt tour mới',
    chooseTour: 'Chọn tour',
    chooseSchedule: 'Chọn lịch khởi hành',
    chooseTourPlaceholder: '-- Chọn tour --',
    chooseSchedulePlaceholder: '-- Chọn lịch --',
    seatsLeft: 'chỗ',
    customerName: 'Khách hàng',
    guestCount: 'Số khách',
    totalAmount: 'Tổng tiền',
    payment: 'Thanh toán',
    action: 'Hành động',
    loading: 'Đang tải...',
    noBookings: 'Chưa có lượt đặt tour nào.',
    confirmPending: 'Chờ xác nhận',
    confirmed: 'Đã xác nhận',
    cancelled: 'Đã huỷ',
    customersTitle: 'Quản lý khách hàng',
    customersHelp: 'Danh sách khách hàng và thông tin liên hệ.',
    addCustomer: 'Thêm khách hàng',
    editCustomer: 'Sửa khách hàng',
    addNewCustomer: 'Thêm khách hàng mới',
    address: 'Địa chỉ',
    cancel: 'Huỷ',
    update: 'Cập nhật',
    add: 'Thêm',
    noCustomers: 'Chưa có khách hàng nào.',
    reportsTitle: 'Báo cáo doanh thu',
    reportsHelp: 'Thống kê tổng hợp và chi tiết theo thời gian.',
    totalTours: 'Tổng tour',
    totalBookings: 'Tổng đặt tour',
    totalCustomers: 'Tổng khách hàng',
    totalGuests: 'Tổng lượt khách',
    topTours: 'Top tour bán chạy',
    fromDate: 'Từ ngày',
    toDate: 'Đến ngày',
    viewReport: 'Xem báo cáo',
    exportBookingsCsv: 'Xuất CSV đặt tour',
    exportRevenueCsv: 'Xuất CSV doanh thu',
    createdDate: 'Ngày tạo',
    revenueChart: 'Biểu đồ doanh thu',
    vnpayTitle: 'Thanh toán VNPay',
    vnpayHelp: 'Quản lý giao dịch và trạng thái thanh toán qua VNPay.',
    vnpayBoard: 'Bảng thanh toán VNPay',
    vnpayComingSoon: 'Thống kê và quản lý giao dịch VNPay chi tiết sẽ được bổ sung ở phiên bản tiếp theo.',
    usersTitle: 'Quản lý người dùng',
    usersHelp: 'Quản lý tài khoản và vai trò truy cập hệ thống.',
    noUsers: 'Chưa có người dùng nào.',
    role: 'Vai trò',
    paid: 'Đã thanh toán',
    vnpayWaiting: 'Chờ VNPay',
    failed: 'Thất bại',
    unpaid: 'Chưa thanh toán',
    tourCode: 'Mã tour',
    tourName: 'Tên tour',
    daysCount: 'Số ngày',
    priceVnd: 'Giá (VNĐ)',
    originalPriceVnd: 'Giá gốc (VNĐ)',
    salePriceVnd: 'Giá sau giảm (VNĐ)',
    discountPercent: 'Phần trăm giảm',
    promotionTitle: 'Tên ưu đãi',
    promotionDescription: 'Mô tả ưu đãi',
    discountStartDate: 'Ngày bắt đầu ưu đãi',
    discountEndDate: 'Ngày kết thúc ưu đãi',
    promotionConfig: 'Cấu hình giảm giá',
    promotionConfigHelp: 'Nhập giá gốc và giá sau giảm, hoặc nhập phần trăm để hệ thống tự tính giá bán.',
    maxGuests: 'Số khách tối đa',
    imageUrl: 'URL hình ảnh',
    description: 'Mô tả',
    activeForSale: 'Đang mở bán',
    updateTour: 'Cập nhật tour',
    addNewTour: 'Thêm tour mới',
    backToTours: 'Quay lại danh sách tour',
    scheduleTitle: 'Lịch khởi hành',
    scheduleHelp: 'Quản lý các đợt khởi hành cho tour này.',
    addSchedule: 'Thêm lịch',
    updateSchedule: 'Cập nhật lịch',
    addNewSchedule: 'Thêm lịch khởi hành',
    startDate: 'Ngày bắt đầu',
    endDate: 'Ngày kết thúc',
    availableSeats: 'Số chỗ còn',
    guide: 'Hướng dẫn viên',
    note: 'Ghi chú',
    openRegistration: 'Mở đăng ký',
    fullStatus: 'Hết chỗ',
    unassigned: 'Chưa phân công',
    departedStatus: 'Đã khởi hành',
    completedStatus: 'Đã kết thúc',
    totalSchedules: 'Tổng lịch',
    bookedSeats: 'Đã đặt',
    available: 'Còn trống',
    scheduleTourTitle: 'Lịch trình tour',
    myGuideSchedule: 'Lịch hướng dẫn của tôi',
    scheduleTourHelp: 'Quản lý đợt khởi hành, phân công hướng dẫn viên và theo dõi số chỗ.',
    myGuideScheduleHelp: 'Theo dõi các chuyến đi được phân công và số lượng khách.',
    searchTourGuide: 'Tìm tour hoặc hướng dẫn viên...',
    allTours: 'Tất cả tour',
    allStatuses: 'Tất cả trạng thái',
    matchingScheduleEmpty: 'Chưa có lịch trình phù hợp.',
    progress: 'Tiến độ',
    selectTour: 'Chọn tour',
    chooseDateForGuides: 'Chọn ngày để xem hướng dẫn viên rảnh.',
    onlyAvailableGuides: 'Chỉ hiển thị hướng dẫn viên đã khai báo rảnh và chưa bị trùng tour.',
    currentGuide: 'Hướng dẫn viên hiện tại',
    internalTripNote: 'Thông tin nội bộ cho chuyến đi',
  },
  en: {
    settingsTitle: 'Settings',
    settingsSubtitle: 'Manage your profile, security, and TraveX notifications.',
    logout: 'Sign out',
    accountTitle: 'Account information',
    accountSubtitle: 'These details are used across the system.',
    fullName: 'Full name',
    username: 'Username',
    phone: 'Phone number',
    saveProfile: 'Save profile',
    securityTitle: 'Security',
    securitySubtitle: 'Update your password regularly to protect the account.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    changePassword: 'Change password',
    notificationsTitle: 'Notifications',
    notificationsSubtitle: 'Choose which updates you want to receive.',
    bookingEmail: 'Booking emails',
    bookingEmailHelp: 'Booking confirmations, payments, and schedule changes.',
    promoEmail: 'Promotion emails',
    promoEmailHelp: 'Seasonal campaign updates and voucher codes.',
    inAppNotifications: 'In-app notifications',
    inAppNotificationsHelp: 'Show reminders and updates inside the dashboard.',
    appearanceTitle: 'Appearance',
    appearanceSubtitle: 'Tune the interface to match how you work.',
    theme: 'Theme',
    language: 'Language',
    systemTheme: 'System',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    compactTables: 'Compact data tables',
    compactTablesHelp: 'Reduce table spacing in management screens.',
    profileSaved: 'Profile information was saved on this device.',
    passwordMissing: 'Please fill in all password fields.',
    passwordShort: 'The new password must be at least 6 characters.',
    passwordMismatch: 'Password confirmation does not match.',
    passwordChecked: 'Password input is valid. A real password API can be connected later.',
    campaignTitle: 'Promotions',
    campaignPublicHeadline: 'Tours with active deals',
    campaignAdminHeadline: 'Manage discounted tours',
    campaignPublicText: 'Quickly browse discounted tours, review clear offers, and book your next trip.',
    campaignAdminText: 'Track discounted tours, promotion dates, and offer content directly from tour data.',
    viewDeals: 'View deals',
    backHome: 'Back home',
    manageTours: 'Manage tours',
    appliedTours: 'Applied tours',
    bestDiscount: 'Best discount',
    daysLeft: 'Time left',
    days: 'days',
    publicCampaignTours: 'Discounted tours',
    adminCampaignTours: 'Tours with promotions',
    publicCampaignHelp: 'Filter by destination, tour type, and budget to find a fitting trip.',
    adminCampaignHelp: 'Filter quickly for consulting or campaign review.',
    searchTour: 'Search destination or tour name',
    maxBudget: 'Max budget',
    loadingCampaign: 'Loading campaign tours...',
    emptyCampaign: 'No tours match the current filters.',
    summerPlaceholder: 'Promotion',
    seeAndBook: 'View and book',
    seeDetails: 'View details',
    home: 'Home',
    tour: 'Tours',
    login: 'Sign in',
    all: 'All',
    island: 'Beach',
    family: 'Family',
    resort: 'Resort',
    explore: 'Explore',
    navDashboard: 'Dashboard',
    navBookings: 'Bookings',
    navSchedule: 'Schedule',
    navCustomers: 'Customers',
    navReports: 'Revenue',
    navVnpay: 'VNPay Payments',
    navUsers: 'Users',
    management: 'Management',
    adminRole: 'Administrator',
    staffRole: 'Guide',
    customerRole: 'Customer',
    adminSearchPlaceholder: 'Search customer name or tour name...',
    totalRevenue: 'Total revenue',
    vsPrevious: 'vs previous period',
    activeTours: 'Active tours',
    closedTours: 'closed tours',
    pendingBookings: 'Pending bookings',
    requestsNeedReview: 'requests need review',
    vnpayPayments: 'VNPay payments',
    revenue: 'Revenue',
    tourPerformance: 'Tour performance',
    viewAll: 'View all',
    viewAllTours: 'View all tours',
    category: 'Category',
    duration: 'Duration',
    priceFrom: 'Price from',
    bookingCount: 'Bookings',
    status: 'Status',
    openStatus: 'Open',
    closedStatus: 'Closed',
    recentActivity: 'Recent activity',
    newBookingRequest: 'New booking request',
    paymentReceived: 'Payment received',
    recentBookings: 'Recent bookings',
    success: 'Success',
    pending: 'Pending',
    totalVnpayRevenue: 'Total VNPay revenue',
    noVnpayPayments: 'No VNPay payments yet.',
    toursListTitle: 'Tour list',
    toursListAdminHelp: 'Manage tour details, destinations, prices, and capacity.',
    toursListCustomerHelp: 'Search and book attractive travel tours.',
    searchTourCodeDestination: 'Search tour, code, destination...',
    addTour: 'Add tour',
    noTours: 'No tours found.',
    destination: 'Destination',
    guests: 'guests',
    capacity: 'Capacity',
    noDescription: 'No description yet.',
    viewBookTicket: 'View details / Book',
    departureSchedule: 'Departure schedule',
    edit: 'Edit',
    delete: 'Delete',
    myTours: 'My tours',
    bookingsListTitle: 'Booking list',
    myToursHelp: 'Manage your booked tours and VNPay payments.',
    bookingsListHelp: 'Manage tour bookings, processing status, and VNPay payments.',
    bookTour: 'Book tour',
    newBooking: 'New booking',
    chooseTour: 'Choose tour',
    chooseSchedule: 'Choose departure schedule',
    chooseTourPlaceholder: '-- Choose tour --',
    chooseSchedulePlaceholder: '-- Choose schedule --',
    seatsLeft: 'seats left',
    customerName: 'Customer',
    guestCount: 'Guests',
    totalAmount: 'Total amount',
    payment: 'Payment',
    action: 'Action',
    loading: 'Loading...',
    noBookings: 'No bookings yet.',
    confirmPending: 'Pending confirmation',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    customersTitle: 'Customer management',
    customersHelp: 'Customer list and contact information.',
    addCustomer: 'Add customer',
    editCustomer: 'Edit customer',
    addNewCustomer: 'Add new customer',
    address: 'Address',
    cancel: 'Cancel',
    update: 'Update',
    add: 'Add',
    noCustomers: 'No customers yet.',
    reportsTitle: 'Revenue reports',
    reportsHelp: 'Summary and detailed statistics by time period.',
    totalTours: 'Total tours',
    totalBookings: 'Total bookings',
    totalCustomers: 'Total customers',
    totalGuests: 'Total guests',
    topTours: 'Best-selling tours',
    fromDate: 'From date',
    toDate: 'To date',
    viewReport: 'View report',
    exportBookingsCsv: 'Export bookings CSV',
    exportRevenueCsv: 'Export revenue CSV',
    createdDate: 'Created date',
    revenueChart: 'Revenue chart',
    vnpayTitle: 'VNPay payments',
    vnpayHelp: 'Manage VNPay transactions and payment statuses.',
    vnpayBoard: 'VNPay payment board',
    vnpayComingSoon: 'Detailed VNPay transaction statistics and management will be added in the next version.',
    usersTitle: 'User management',
    usersHelp: 'Manage accounts and system access roles.',
    noUsers: 'No users yet.',
    role: 'Role',
    paid: 'Paid',
    vnpayWaiting: 'Waiting for VNPay',
    failed: 'Failed',
    unpaid: 'Unpaid',
    tourCode: 'Tour code',
    tourName: 'Tour name',
    daysCount: 'Number of days',
    priceVnd: 'Price (VND)',
    originalPriceVnd: 'Original price (VND)',
    salePriceVnd: 'Sale price (VND)',
    discountPercent: 'Discount percent',
    promotionTitle: 'Promotion title',
    promotionDescription: 'Promotion description',
    discountStartDate: 'Promotion start date',
    discountEndDate: 'Promotion end date',
    promotionConfig: 'Discount configuration',
    promotionConfigHelp: 'Enter original and sale prices, or enter a percent so the sale price is calculated automatically.',
    maxGuests: 'Max guests',
    imageUrl: 'Image URL',
    description: 'Description',
    activeForSale: 'Open for sale',
    updateTour: 'Update tour',
    addNewTour: 'Add new tour',
    backToTours: 'Back to tour list',
    scheduleTitle: 'Departure schedule',
    scheduleHelp: 'Manage departure batches for this tour.',
    addSchedule: 'Add schedule',
    updateSchedule: 'Update schedule',
    addNewSchedule: 'Add departure schedule',
    startDate: 'Start date',
    endDate: 'End date',
    availableSeats: 'Available seats',
    guide: 'Guide',
    note: 'Note',
    openRegistration: 'Open registration',
    fullStatus: 'Full',
    unassigned: 'Unassigned',
    departedStatus: 'Departed',
    completedStatus: 'Completed',
    totalSchedules: 'Total schedules',
    bookedSeats: 'Booked',
    available: 'Available',
    scheduleTourTitle: 'Tour schedule',
    myGuideSchedule: 'My guide schedule',
    scheduleTourHelp: 'Manage departures, assign guides, and track available seats.',
    myGuideScheduleHelp: 'Track assigned trips and guest counts.',
    searchTourGuide: 'Search tour or guide...',
    allTours: 'All tours',
    allStatuses: 'All statuses',
    matchingScheduleEmpty: 'No matching schedules.',
    progress: 'Progress',
    selectTour: 'Select tour',
    chooseDateForGuides: 'Choose dates to see available guides.',
    onlyAvailableGuides: 'Only guides who declared availability and are not assigned to another tour are shown.',
    currentGuide: 'Current guide',
    internalTripNote: 'Internal trip notes',
  },
}

const SettingsContext = createContext(null)

function loadSettings() {
  try {
    return { ...DEFAULT_SETTINGS, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') }
  } catch {
    return DEFAULT_SETTINGS
  }
}

function getResolvedTheme(theme) {
  return 'light'
}

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState(loadSettings)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(settings))
  }, [settings])

  useEffect(() => {
    const root = document.documentElement
    const resolvedTheme = getResolvedTheme(settings.theme)
    root.dataset.theme = resolvedTheme
    root.dataset.language = settings.language
    root.classList.toggle('theme-dark', resolvedTheme === 'dark')
    root.classList.toggle('theme-light', resolvedTheme === 'light')
    root.classList.toggle('compact-tables', settings.compactTables)
  }, [settings.compactTables, settings.language, settings.theme])

  const value = useMemo(() => {
    const updateSetting = (name, value) => {
      setSettings(prev => ({ ...prev, [name]: value }))
    }

    const t = (key) => DICTIONARY[settings.language]?.[key] || DICTIONARY.vi[key] || key

    return { settings, updateSetting, t }
  }, [settings])

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  )
}

export function useSettings() {
  const ctx = useContext(SettingsContext)
  if (!ctx) throw new Error('useSettings must be used within SettingsProvider')
  return ctx
}
